import { ConflictException, Injectable } from '@nestjs/common';
import { CourseStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { normalizePagination, paginationMeta } from '../../common/pagination';
import { notFound } from '../../common/http-errors';
import { CreateCourseDto } from './dto/create-course.dto';
import { ListCourseDto } from './dto/list-course.dto';
import { UpdateCourseDto } from './dto/update-course.dto';
@Injectable()
export class CoursesService { constructor(private readonly prisma: PrismaService) {} async findAll(query: ListCourseDto) { const pagination = normalizePagination(query); const where: Prisma.CourseWhereInput = { ...(query.level ? { level: query.level } : {}), ...(query.status ? { status: query.status } : {}), ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { code: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const [courses, total] = await this.prisma.$transaction([this.prisma.course.findMany({ where, include: { _count: { select: { classes: true } } }, orderBy: { createdAt: 'desc' }, skip: pagination.skip, take: pagination.take }), this.prisma.course.count({ where })]); return { data: courses.map((course) => ({ id: course.id.toString(), code: course.code, name: course.name, level: course.level, totalLessons: course.totalLessons, tuition: course.tuition.toString(), classCount: course._count.classes, status: course.status })), meta: paginationMeta(pagination.page, pagination.pageSize, total) }; } async findOne(id: string) { const course = await this.prisma.course.findUnique({ where: { id: BigInt(id) }, include: { classes: true } }); if (!course) notFound('Course', id); return { ...course, id: course.id.toString(), tuition: course.tuition.toString(), classes: course.classes.map((item) => ({ ...item, id: item.id.toString(), courseId: item.courseId.toString(), teacherId: item.teacherId.toString() })) }; } async create(dto: CreateCourseDto) { try { const course = await this.prisma.course.create({ data: { ...dto, status: CourseStatus.ACTIVE } }); return { ...course, id: course.id.toString(), tuition: course.tuition.toString() }; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException('Course code already exists'); throw error; } } async update(id: string, dto: UpdateCourseDto) { const course = await this.prisma.course.update({ where: { id: BigInt(id) }, data: dto }); return { ...course, id: course.id.toString(), tuition: course.tuition.toString() }; } }
