services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env
    environment:
      NODE_ENV: development
      API_PORT: 4000
      WEB_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"

  web:
    build:
      context: ./apps/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
