import { BadRequestException, ConflictException, Injectable } from '@nestjs/common';
import { EnrollmentStatus, Prisma, TestType, UserRole } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { normalizePagination, paginationMeta } from '../../common/pagination';
import { notFound } from '../../common/http-errors';
import type { AuthPayload } from '../auth/auth.types';
import { TeachingAccessService } from '../teaching/teaching-access.service';
import { CreateTestDto } from './dto/create-test.dto';
import { ListTestDto } from './dto/list-test.dto';
import { UpdateScoresDto } from './dto/update-scores.dto';
import { AuditService } from '../audit/audit.service';

@Injectable()
export class ScoresService {
  constructor(private readonly prisma: PrismaService, private readonly access: TeachingAccessService, private readonly audit: AuditService) {}

  async findTestsByClass(classId: string, query: ListTestDto, user: AuthPayload) { await this.access.assertClass(classId, user, false); const pagination = normalizePagination(query); const where: Prisma.TestWhereInput = { classId: BigInt(classId), ...(query.type ? { type: query.type } : {}) }; const [tests, total] = await this.prisma.$transaction([this.prisma.test.findMany({ where, include: { _count: { select: { scores: true } } }, orderBy: { testDate: 'desc' }, skip: pagination.skip, take: pagination.take }), this.prisma.test.count({ where })]); return { data: tests.map((test) => this.testResponse(test)), meta: paginationMeta(pagination.page, pagination.pageSize, total) }; }
  async createTest(dto: CreateTestDto, user: AuthPayload) { await this.access.assertClass(dto.classId, user, true); const test = await this.prisma.test.create({ data: { classId: BigInt(dto.classId), name: dto.name, type: dto.type, maxScore: dto.maxScore, testDate: dto.testDate ? new Date(dto.testDate) : undefined }, include: { _count: { select: { scores: true } } } }); return this.testResponse(test); }
  async findScores(testId: string, user: AuthPayload) { const test = await this.access.assertTest(testId, user, false); const enrollments = await this.prisma.enrollment.findMany({ where: { classId: test.classId, status: { in: [EnrollmentStatus.ACTIVE, EnrollmentStatus.COMPLETED] } }, include: { student: { include: { user: true, scores: { where: { testId: BigInt(testId) } } } } }, orderBy: { student: { studentCode: 'asc' } } }); const ownStudentId = user.role === UserRole.STUDENT ? (await this.prisma.student.findUnique({ where: { userId: BigInt(user.sub) } }))?.id : null; const visible = ownStudentId ? enrollments.filter((enrollment) => enrollment.studentId === ownStudentId) : enrollments; return { test: { id: test.id.toString(), classId: test.classId.toString(), name: test.name, type: test.type, maxScore: Number(test.maxScore) }, data: visible.map((enrollment) => this.scoreResponse(enrollment.student, enrollment.student.scores[0], test.id)) }; }
  async updateScores(testId: string, dto: UpdateScoresDto, user: AuthPayload) { const test = await this.access.assertTest(testId, user, true); const enrollments = await this.prisma.enrollment.findMany({ where: { classId: test.classId, status: { in: [EnrollmentStatus.ACTIVE, EnrollmentStatus.COMPLETED] } }, select: { studentId: true } }); const allowed = new Set(enrollments.map((item) => item.studentId.toString())); const uniqueStudents = new Set(dto.entries.map((entry) => entry.studentId)); if (uniqueStudents.size !== dto.entries.length) throw new BadRequestException('Duplicate student in score payload'); if (dto.entries.some((entry) => !allowed.has(entry.studentId))) throw new BadRequestException('Every student must belong to the class'); if (dto.entries.some((entry) => entry.value !== null && entry.value !== undefined && entry.value > Number(test.maxScore))) throw new BadRequestException(`Score cannot exceed ${test.maxScore}`); try { await this.prisma.$transaction(dto.entries.map((entry) => entry.value === null || entry.value === undefined ? this.prisma.score.deleteMany({ where: { testId: BigInt(testId), studentId: BigInt(entry.studentId) } }) : this.prisma.score.upsert({ where: { testId_studentId: { testId: BigInt(testId), studentId: BigInt(entry.studentId) } }, update: { value: entry.value, note: entry.note ?? null }, create: { testId: BigInt(testId), studentId: BigInt(entry.studentId), value: entry.value, note: entry.note ?? null } }))); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException('Score entry already exists'); throw error; } await this.audit.write({ actorId: user.sub, action: 'UPDATE', entity: 'Score', entityId: testId, newValue: { count: dto.entries.length } }); return this.findScores(testId, user); }
  private testResponse(test: any) { return { id: test.id.toString(), classId: test.classId.toString(), name: test.name, type: test.type as TestType, maxScore: Number(test.maxScore), testDate: test.testDate, scoreCount: test._count?.scores ?? 0 }; }
  private scoreResponse(student: any, score: any, testId: bigint) { return { id: score?.id?.toString() ?? `${testId.toString()}-${student.id.toString()}`, testId: score?.testId?.toString() ?? testId.toString(), studentId: student.id.toString(), code: student.studentCode, fullName: student.user.fullName, value: score ? Number(score.value) : null, note: score?.note ?? null }; }
}
