import type { AttendanceEntry, ScoreEntry, TeacherLessonOption, TeacherTestOption } from '@/types';
import { apiClient } from '@/lib/api-client';

export interface TeacherAssessmentSourceOptions { forceApi?: boolean; }

export const teacherAssessmentService = {
  async getLessons(classId?: number): Promise<TeacherLessonOption[]> { if (!classId) return []; const response = await apiClient<{ data: Array<{ id: string; classId: string; title: string; lessonDate: string }> }>(`/classes/${classId}/lessons`); return response.data.map((lesson) => ({ id: Number(lesson.id), classId: Number(lesson.classId), label: lesson.title, date: lesson.lessonDate.slice(0, 10) })); },
  async getTests(classId?: number, _options: TeacherAssessmentSourceOptions = {}): Promise<TeacherTestOption[]> { if (!classId) return []; const response = await apiClient<{ data: Array<{ id: string; classId: string; name: string; testDate?: string | null }> }>(`/classes/${classId}/tests`); return response.data.map((test) => ({ id: Number(test.id), classId: Number(test.classId), label: test.name, date: test.testDate?.slice(0, 10) ?? '' })); },
  async getAttendance(lessonId: number): Promise<AttendanceEntry[]> { const response = await apiClient<{ data: AttendanceEntry[] }>(`/lessons/${lessonId}/attendance`); return response.data.map((entry) => ({ ...entry, lessonId, status: entry.status ?? 'ABSENT' })); },
  async updateAttendance(lessonId: number, entries: AttendanceEntry[]) { return apiClient<{ data: AttendanceEntry[] }>(`/lessons/${lessonId}/attendance`, { method: 'PUT', body: JSON.stringify({ entries: entries.map(({ studentId, status, note }) => ({ studentId: String(studentId), status, note })) }) }); },
  async getScores(testId: number, _options: TeacherAssessmentSourceOptions = {}): Promise<ScoreEntry[]> { const response = await apiClient<{ data: Array<{ id: string; testId: string; studentId: string; code: string; fullName: string; value: number | null; note?: string | null }> }>(`/tests/${testId}/scores`); return response.data.map((entry) => ({ ...entry, id: Number(entry.id) || entry.id, testId: Number(entry.testId), studentId: Number(entry.studentId), value: entry.value === null ? null : Number(entry.value), note: entry.note ?? '' })); },
  async updateScores(testId: number, entries: ScoreEntry[], _options: TeacherAssessmentSourceOptions = {}) { const response = await apiClient<{ data: Array<{ id: string; testId: string; studentId: string; code: string; fullName: string; value: number | null; note?: string | null }> }>(`/tests/${testId}/scores`, { method: 'PUT', body: JSON.stringify({ entries: entries.map(({ studentId, value, note }) => ({ studentId: String(studentId), value, note })) }) }); return response.data.map((entry) => ({ ...entry, id: Number(entry.id) || entry.id, testId: Number(entry.testId), studentId: Number(entry.studentId), value: entry.value === null ? null : Number(entry.value), note: entry.note ?? '' })); },
};
