'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock3, FileText, LayoutList, Link2, MessageCircle, Paperclip, UsersRound } from 'lucide-react';
import { Avatar } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { buttonVariants } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { ClassTheme, ClassWork, StudentAssignment, StudentAssignmentStatus, StudentClassDetail, StudentClassMaterial } from '@/types';
import { cn } from '@/lib/utils';

type DetailTab = 'STREAM' | 'WORK' | 'PEOPLE';
const themes: Record<ClassTheme, string> = { emerald: 'from-emerald-400 to-teal-600', violet: 'from-violet-500 to-indigo-700', amber: 'from-amber-400 to-orange-600', rose: 'from-rose-400 to-pink-600', sky: 'from-sky-400 to-cyan-600' };

export function StudentClassDetail({ classDetail }: { classDetail: StudentClassDetail }) {
  const [tab, setTab] = useState<DetailTab>('STREAM');
  const progress = classDetail.totalLessons ? Math.round((classDetail.completedLessons / classDetail.totalLessons) * 100) : 0;

  return <div className="mx-auto max-w-6xl"><Link href="/student/classes" className="mb-5 inline-flex items-center gap-2 text-xs font-medium text-slate-500 hover:text-emerald-600"><ArrowLeft className="size-3.5" />Quay lại lớp học của tôi</Link><section className={cn('relative mb-5 min-h-48 overflow-hidden rounded-2xl bg-gradient-to-br p-6 text-white shadow-sm sm:p-8', themes[classDetail.theme])}><div className="absolute -right-12 -top-20 size-64 rounded-full border-[28px] border-white/10" /><div className="absolute -bottom-28 right-32 size-64 rounded-full border-[24px] border-white/10" /><div className="relative flex min-h-32 flex-col justify-end"><p className="text-sm font-medium text-white/80">{classDetail.code} · {classDetail.section}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">{classDetail.name}</h1><p className="mt-2 text-sm text-white/80">Giáo viên: {classDetail.teacherName}</p></div></section><div className="mb-6 flex gap-1 overflow-x-auto border-b border-slate-100">{([{ key: 'STREAM', label: 'Bảng tin', icon: LayoutList }, { key: 'WORK', label: 'Bài tập & tài liệu', icon: BookOpen }, { key: 'PEOPLE', label: 'Mọi người', icon: UsersRound }] as const).map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={cn('flex shrink-0 items-center gap-2 border-b-2 px-4 pb-3 text-sm font-medium', tab === item.key ? 'border-emerald-500 text-emerald-600' : 'border-transparent text-slate-500 hover:text-slate-800')}><item.icon className="size-4" />{item.label}</button>)}</div>{tab === 'STREAM' && <StreamView classDetail={classDetail} progress={progress} />}{tab === 'WORK' && <WorkView classId={classDetail.id} works={classDetail.works ?? []} assignments={classDetail.assignments ?? []} materials={classDetail.materials ?? []} />}{tab === 'PEOPLE' && <PeopleView classDetail={classDetail} />}</div>;
}

function StreamView({ classDetail, progress }: { classDetail: StudentClassDetail; progress: number }) {
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><main className="space-y-4"><Card><CardContent className="flex items-center gap-3 p-4"><Avatar initials="N" className="size-9 bg-emerald-50 text-emerald-600" /><button className="flex h-10 flex-1 items-center rounded-full border border-slate-200 px-4 text-left text-sm text-slate-400 hover:border-emerald-300">Chia sẻ điều gì đó với lớp học...</button></CardContent></Card>{classDetail.announcements.map((announcement) => <Card key={announcement.id}><CardContent className="p-5"><div className="flex items-center gap-3"><Avatar initials={announcement.initials} /><div><p className="text-sm font-semibold text-slate-700">{announcement.author}</p><p className="text-xs text-slate-400">{announcement.time}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{announcement.message}</p><div className="mt-4 flex gap-4 border-t pt-3 text-xs text-slate-400"><span className="flex items-center gap-1.5"><MessageCircle className="size-3.5" />0 nhận xét</span><button className="text-emerald-600 hover:underline">Thêm nhận xét</button></div></CardContent></Card>)}</main><aside className="space-y-4"><Card><CardHeader className="pb-3"><CardTitle className="text-sm">Thông tin lớp học</CardTitle></CardHeader><CardContent className="space-y-3 text-xs text-slate-500"><InfoRow icon={<CalendarDays />} text={classDetail.schedule} /><InfoRow icon={<BookOpen />} text={classDetail.room} /><InfoRow icon={<UsersRound />} text={`${classDetail.studentCount} học viên`} /><div className="border-t pt-3"><div className="mb-1.5 flex justify-between"><span>Tiến độ khóa học</span><b className="text-emerald-600">{progress}%</b></div><div className="h-1.5 rounded-full bg-emerald-50"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${progress}%` }} /></div></div></CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="text-sm">Tài nguyên lớp học</CardTitle></CardHeader><CardContent className="space-y-3 text-xs text-slate-500"><InfoRow icon={<Link2 />} text="Nhóm trao đổi lớp học" /><InfoRow icon={<FileText />} text="Tài liệu học tập chung" /></CardContent></Card></aside></div>;
}

function WorkView({ classId, works, assignments, materials }: { classId: number; works: ClassWork[]; assignments: StudentAssignment[]; materials: StudentClassMaterial[] }) {
  const assignmentRows = assignments.length ? assignments : works.filter((work) => work.type === 'ASSIGNMENT').map((work) => ({ id: work.id, title: work.title, description: work.description, dueAt: work.dueDate, status: work.status === 'COMPLETED' ? 'SUBMITTED' : 'PENDING', submission: null }) satisfies StudentAssignment);
  const resources = works.filter((work) => work.type !== 'ASSIGNMENT');

  return <div className="mx-auto max-w-3xl space-y-5"><section className="space-y-3">{assignmentRows.map((assignment) => { const meta = assignmentMeta[assignment.status]; return <Card key={assignment.id} className="border-slate-200 shadow-sm transition-colors hover:border-emerald-200"><CardContent className="flex items-center gap-4 p-5"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-600"><Paperclip className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-800">{assignment.title}</h3><Badge variant={meta.variant}>{meta.label}</Badge></div><p className="mt-1 flex items-center gap-1.5 text-xs text-slate-500"><Clock3 className="size-3.5" />Hạn nộp: {formatDeadline(assignment.dueAt)}</p></div><Link href={`/student/classes/${classId}/assignments/${assignment.id}`} className={buttonVariants({ variant: 'outline', size: 'sm' })}>Xem chi tiết</Link></CardContent></Card>; })}</section>{resources.length > 0 && <div className="space-y-3"><h3 className="text-sm font-semibold text-slate-800">Tài liệu và buổi học</h3>{resources.map((work) => <ResourceCard key={work.id} work={work} />)}</div>}{materials.length > 0 && <div className="space-y-3"><h3 className="text-sm font-semibold text-slate-800">Tài liệu bài giảng</h3>{materials.map((material) => <MaterialResourceCard key={material.id} material={material} />)}</div>}{assignmentRows.length === 0 && resources.length === 0 && materials.length === 0 && <Card><CardContent className="p-10 text-center text-sm text-slate-500">Chưa có bài tập hoặc tài liệu nào cho lớp học này.</CardContent></Card>}</div>;
}

const assignmentMeta: Record<StudentAssignmentStatus, { label: string; variant: 'warning' | 'success' | 'danger' | 'secondary' }> = { PENDING: { label: 'Chưa nộp', variant: 'warning' }, OVERDUE: { label: 'Quá hạn', variant: 'danger' }, SUBMITTED: { label: 'Đã nộp', variant: 'success' }, LATE: { label: 'Đã nộp trễ', variant: 'danger' } };

function ResourceCard({ work }: { work: ClassWork }) { return <Card className="transition-colors hover:border-emerald-200"><CardContent className="flex items-center gap-4 p-4 sm:p-5"><div className={cn('grid size-10 shrink-0 place-items-center rounded-full', work.type === 'MATERIAL' ? 'bg-slate-100 text-slate-500' : 'bg-emerald-50 text-emerald-600')}>{work.type === 'MATERIAL' ? <FileText className="size-5" /> : <BookOpen className="size-5" />}</div><div className="min-w-0 flex-1"><p className="font-medium text-slate-700">{work.title}</p><p className="mt-1 text-xs text-slate-400">{work.description}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-slate-500"><Clock3 className="size-3.5" />{work.dueDate}</p></div><Badge variant="secondary">Tài liệu</Badge></CardContent></Card>; }
function MaterialResourceCard({ material }: { material: StudentClassMaterial }) { return <Card className="transition-colors hover:border-emerald-200"><CardContent className="flex items-center gap-4 p-4 sm:p-5"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-500"><FileText className="size-5" /></div><div className="min-w-0 flex-1"><p className="font-medium text-slate-700">{material.title}</p><p className="mt-1 truncate text-xs text-slate-400">{material.fileName}</p><p className="mt-2 text-xs text-slate-500">{material.lessonTitle || material.description || 'Tài liệu chung của lớp'}</p></div>{material.downloadUrl ? <a href={material.downloadUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-emerald-600 hover:underline">Mở file</a> : <Badge variant="secondary">Tài liệu</Badge>}</CardContent></Card>; }

function PeopleView({ classDetail }: { classDetail: StudentClassDetail }) {
  const pageSize = 20;
  const [page, setPage] = useState(1);
  const teacher = classDetail.people.find((person) => person.role === 'TEACHER');
  const students = classDetail.people.filter((person) => person.role === 'STUDENT');
  const totalPages = Math.max(1, Math.ceil(students.length / pageSize));
  const visibleStudents = students.slice((page - 1) * pageSize, page * pageSize);

  useEffect(() => { setPage(1); }, [classDetail.id]);
  useEffect(() => { if (page > totalPages) setPage(totalPages); }, [page, totalPages]);

  return <div className="mx-auto max-w-3xl space-y-6"><Card><CardHeader><CardTitle className="text-base">Giáo viên</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3"><Avatar initials={teacher?.initials ?? classDetail.teacherInitials} className="bg-emerald-50 text-emerald-600" /><div><p className="text-sm font-semibold">{teacher?.fullName ?? classDetail.teacherName}</p><p className="text-xs text-slate-400">Giáo viên lớp</p></div></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Học viên · {classDetail.studentCount}</CardTitle></CardHeader><CardContent className="grid gap-1 sm:grid-cols-2">{visibleStudents.map((student) => <div className="flex items-center gap-3 rounded-lg p-2.5 hover:bg-slate-50" key={student.id}><Avatar initials={student.initials} className="size-8" /><p className="text-sm text-slate-600">{student.fullName}</p></div>)}{students.length === 0 && <p className="py-6 text-sm text-slate-500 sm:col-span-2">Chưa có học viên trong lớp.</p>}<div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-4 text-xs text-slate-500 sm:col-span-2"><span>Trang {page}/{totalPages} · {students.length} học viên</span><div className="flex items-center gap-2"><button type="button" aria-label="Trang trước" disabled={page === 1} onClick={() => setPage((current) => Math.max(1, current - 1))} className="inline-flex size-8 items-center justify-center rounded-md border border-slate-200 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"><ChevronLeft className="size-4" /></button><button type="button" aria-label="Trang sau" disabled={page === totalPages} onClick={() => setPage((current) => Math.min(totalPages, current + 1))} className="inline-flex size-8 items-center justify-center rounded-md border border-slate-200 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"><ChevronRight className="size-4" /></button></div></div></CardContent></Card></div>;
}

function InfoRow({ icon, text }: { icon: React.ReactNode; text: string }) { return <p className="flex items-center gap-2"><span className="text-emerald-500 [&>svg]:size-3.5">{icon}</span>{text}</p>; }

function formatDeadline(value: string) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(parsed); }
