import { ConflictException, Injectable } from '@nestjs/common';
import { ClassStatus, EnrollmentStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { normalizePagination, paginationMeta } from '../../common/pagination';
import { notFound } from '../../common/http-errors';
import { CreateClassDto } from './dto/create-class.dto';
import { ListClassDto } from './dto/list-class.dto';
import { UpdateClassDto } from './dto/update-class.dto';

@Injectable()
export class ClassesService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(query: ListClassDto) { const pagination = normalizePagination(query); const where: Prisma.ClassWhereInput = { ...(query.status ? { status: query.status } : {}), ...(query.courseId ? { courseId: BigInt(query.courseId) } : {}), ...(query.teacherId ? { teacherId: BigInt(query.teacherId) } : {}), ...(query.search ? { OR: [{ code: { contains: query.search, mode: 'insensitive' } }, { name: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const [classes, total] = await this.prisma.$transaction([this.prisma.class.findMany({ where, include: { course: true, teacher: { include: { user: true } }, _count: { select: { enrollments: true, lessons: true } } }, orderBy: { startDate: 'desc' }, skip: pagination.skip, take: pagination.take }), this.prisma.class.count({ where })]); return { data: classes.map((item) => this.toResponse(item)), meta: paginationMeta(pagination.page, pagination.pageSize, total) }; }
  async findOne(id: string) { const classRoom = await this.prisma.class.findUnique({ where: { id: BigInt(id) }, include: { course: true, teacher: { include: { user: true } }, enrollments: { where: { status: EnrollmentStatus.ACTIVE }, include: { student: { include: { user: true } } } }, lessons: true, tests: true } }); if (!classRoom) notFound('Class', id); return { ...this.toResponse(classRoom), students: classRoom.enrollments.map((item) => ({ id: item.student.id.toString(), code: item.student.studentCode, fullName: item.student.user.fullName, email: item.student.user.email })) }; }
  async create(dto: CreateClassDto) { try { const item = await this.prisma.class.create({ data: { code: dto.code, name: dto.name, courseId: BigInt(dto.courseId), teacherId: BigInt(dto.teacherId), startDate: new Date(dto.startDate), endDate: dto.endDate ? new Date(dto.endDate) : undefined, schedule: dto.schedule, room: dto.room, capacity: dto.capacity, status: ClassStatus.UPCOMING }, include: { course: true, teacher: { include: { user: true } }, _count: { select: { enrollments: true, lessons: true } } } }); return this.toResponse(item); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException('Class code already exists'); throw error; } }
  async update(id: string, dto: UpdateClassDto) { const item = await this.prisma.class.update({ where: { id: BigInt(id) }, data: { ...(dto.code ? { code: dto.code } : {}), ...(dto.name ? { name: dto.name } : {}), ...(dto.courseId ? { courseId: BigInt(dto.courseId) } : {}), ...(dto.teacherId ? { teacherId: BigInt(dto.teacherId) } : {}), ...(dto.startDate ? { startDate: new Date(dto.startDate) } : {}), ...(dto.endDate ? { endDate: new Date(dto.endDate) } : {}), ...(dto.schedule ? { schedule: dto.schedule } : {}), ...(dto.room !== undefined ? { room: dto.room } : {}), ...(dto.capacity ? { capacity: dto.capacity } : {}) }, include: { course: true, teacher: { include: { user: true } }, _count: { select: { enrollments: true, lessons: true } } } }); return this.toResponse(item); }
  async enroll(classId: string, studentId: string) { const result = await this.prisma.$transaction(async (tx) => { const classRoom = await tx.class.findUnique({ where: { id: BigInt(classId) }, include: { _count: { select: { enrollments: true } } } }); if (!classRoom) notFound('Class', classId); const student = await tx.student.findUnique({ where: { id: BigInt(studentId) } }); if (!student) notFound('Student', studentId); const existing = await tx.enrollment.findUnique({ where: { studentId_classId: { studentId: BigInt(studentId), classId: BigInt(classId) } } }); if (existing?.status === EnrollmentStatus.ACTIVE) throw new ConflictException('Student is already enrolled in this class'); if (!existing && classRoom._count.enrollments >= classRoom.capacity) throw new ConflictException('Class is full'); return existing ? tx.enrollment.update({ where: { id: existing.id }, data: { status: EnrollmentStatus.ACTIVE, enrolledAt: new Date(), leftAt: null } }) : tx.enrollment.create({ data: { classId: BigInt(classId), studentId: BigInt(studentId), status: EnrollmentStatus.ACTIVE } }); }); return { id: result.id.toString(), classId: result.classId.toString(), studentId: result.studentId.toString(), status: result.status }; }
  async removeEnrollment(classId: string, studentId: string) { const existing = await this.prisma.enrollment.findUnique({ where: { studentId_classId: { studentId: BigInt(studentId), classId: BigInt(classId) } } }); if (!existing || existing.status !== EnrollmentStatus.ACTIVE) notFound('Enrollment', `${classId}/${studentId}`); const result = await this.prisma.enrollment.update({ where: { id: existing.id }, data: { status: EnrollmentStatus.CANCELLED, leftAt: new Date() } }); return { id: result.id.toString(), classId: result.classId.toString(), studentId: result.studentId.toString(), status: result.status }; }
  private toResponse(item: any) { return { id: item.id.toString(), code: item.code, name: item.name, courseName: item.course.name, courseId: item.courseId?.toString(), teacherName: item.teacher.user.fullName, teacherId: item.teacherId?.toString(), startDate: item.startDate, endDate: item.endDate, schedule: item.schedule, room: item.room, studentCount: item._count?.enrollments ?? item.enrollments?.length ?? 0, capacity: item.capacity, lessonCount: item._count?.lessons ?? item.lessons?.length ?? 0, status: item.status }; }
}
