import { Injectable } from '@nestjs/common';
import { ClassStatus, EnrollmentStatus, Prisma, UserRole, UserStatus } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { ReportFilterDto } from './dto/report-filter.dto';

@Injectable()
export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}

  async getDirectorDashboard() {
    const [students, newStudents, teachers, activeClasses, enrollments, attendance, scores] = await this.prisma.$transaction([this.prisma.student.count({ where: { user: { status: UserStatus.ACTIVE } } }), this.prisma.student.count({ where: { createdAt: { gte: this.daysAgo(30) } } }), this.prisma.teacher.count({ where: { user: { status: UserStatus.ACTIVE } } }), this.prisma.class.count({ where: { status: ClassStatus.ACTIVE } }), this.prisma.enrollment.count({ where: { status: EnrollmentStatus.ACTIVE } }), this.prisma.attendance.findMany({ select: { status: true } }), this.prisma.score.findMany({ select: { value: true } })]); const present = attendance.filter((item) => item.status === 'PRESENT').length; const late = attendance.filter((item) => item.status === 'LATE').length; const averageScore = scores.length ? Number((scores.reduce((sum, item) => sum + Number(item.value), 0) / scores.length).toFixed(1)) : 0; const capacity = await this.prisma.class.aggregate({ where: { status: ClassStatus.ACTIVE }, _sum: { capacity: true } }); const monthly = await this.monthlyStudentCounts(); return { stats: [{ label: 'Tổng học viên', value: String(students), change: `+${newStudents} trong 30 ngày`, trend: 'up', icon: 'users' }, { label: 'Học viên mới', value: String(newStudents), change: 'Trong 30 ngày qua', trend: 'up', icon: 'user' }, { label: 'Tỷ lệ chuyên cần', value: `${attendance.length ? Math.round(((present + late) / attendance.length) * 100) : 0}%`, change: `${present} có mặt`, trend: 'up', icon: 'check' }, { label: 'Tỷ lệ lấp đầy lớp', value: `${capacity._sum.capacity ? Math.round((enrollments / capacity._sum.capacity) * 100) : 0}%`, change: `${activeClasses} lớp đang hoạt động`, trend: 'neutral', icon: 'chart' }], averageScore, monthlyStudents: monthly, attendance: [{ total: attendance.length, present, late, absent: attendance.length - present - late }], activeClasses };
  }

  async getReports(filter: ReportFilterDto) {
    const classWhere: Prisma.ClassWhereInput = { ...(filter.classId ? { id: BigInt(filter.classId) } : {}), ...(filter.teacherId ? { teacherId: BigInt(filter.teacherId) } : {}) };
    const studentWhere: Prisma.StudentWhereInput = { ...(filter.level ? { currentLevel: filter.level } : {}), user: { status: UserStatus.ACTIVE } };
    const [students, classes, teachers, attendance, scores] = await this.prisma.$transaction([this.prisma.student.findMany({ where: studentWhere, select: { currentLevel: true } }), this.prisma.class.findMany({ where: classWhere, include: { course: true, teacher: { include: { user: true } }, enrollments: { where: { status: EnrollmentStatus.ACTIVE } }, lessons: { include: { attendance: true } } }, orderBy: { code: 'asc' } }), this.prisma.teacher.findMany({ where: { user: { status: UserStatus.ACTIVE } }, include: { user: true, classes: { include: { enrollments: { where: { status: EnrollmentStatus.ACTIVE } } } } } }), this.prisma.attendance.findMany({ select: { status: true } }), this.prisma.score.findMany({ select: { value: true } })]); const levels = ['N5', 'N4', 'N3', 'N2', 'N1']; const studentByLevel = levels.map((level) => ({ level, active: students.filter((item) => item.currentLevel === level).length })); const classReport = classes.map((item) => { const records = item.lessons.flatMap((lesson) => lesson.attendance); const present = records.filter((record) => record.status === 'PRESENT' || record.status === 'LATE').length; return { code: item.code, course: item.course.name, teacher: item.teacher.user.fullName, students: item.enrollments.length, capacity: item.capacity, attendance: records.length ? Math.round((present / records.length) * 100) : 0 }; }); const teacherReport = teachers.map((teacher) => { const teacherClasses = teacher.classes; const totalStudents = teacherClasses.reduce((sum, item) => sum + item.enrollments.length, 0); return { name: teacher.user.fullName, classes: teacherClasses.length, students: totalStudents, attendance: 0, averageScore: 0 }; }); const present = attendance.filter((item) => item.status === 'PRESENT' || item.status === 'LATE').length; const averageScore = scores.length ? Number((scores.reduce((sum, item) => sum + Number(item.value), 0) / scores.length).toFixed(1)) : 0; return { summary: [{ label: 'Tổng học viên', value: String(students.length), note: filter.level ? `Trình độ ${filter.level}` : 'Theo bộ lọc hiện tại' }, { label: 'Tỷ lệ chuyên cần', value: `${attendance.length ? Math.round((present / attendance.length) * 100) : 0}%`, note: `${attendance.length} lượt điểm danh` }, { label: 'Điểm trung bình', value: averageScore.toFixed(1), note: `${scores.length} bài đã nhập điểm` }, { label: 'Lớp học', value: String(classes.length), note: 'Theo bộ lọc hiện tại' }], studentByLevel: studentByLevel.map((item) => ({ ...item, newStudents: 0, completed: 0 })), classReport, teacherReport }; }

  private daysAgo(days: number) { return new Date(Date.now() - days * 24 * 60 * 60 * 1000); }
  private async monthlyStudentCounts() { const result: { month: string; students: number; newStudents: number }[] = []; for (let index = 5; index >= 0; index -= 1) { const start = new Date(); start.setUTCDate(1); start.setUTCMonth(start.getUTCMonth() - index); const end = new Date(start); end.setUTCMonth(end.getUTCMonth() + 1); const count = await this.prisma.student.count({ where: { createdAt: { lt: end } } }); const newStudents = await this.prisma.student.count({ where: { createdAt: { gte: start, lt: end } } }); result.push({ month: `T${start.getUTCMonth() + 1}`, students: count, newStudents }); } return result; }
}
